version: 0.2
phases:
  install:
    commands:
      - echo Installing .NET 7.0 SDK...
      - curl -sSL https://dotnet.microsoft.com/download/dotnet/thank-you/sdk-7.0.100-linux-x64-binaries | sudo bash
      - dotnet --version
  pre_build:
    commands:
      - dotnet restore CarPoolingWebAPI
  build:
    commands:
      - dotnet publish CarPoolingWebAPI/CarPoolingWebAPI.sln -c Release -o ./output
artifacts:
  files:
    - output/**/*
    
