version: 0.2
phases:
  install:
    runtime-versions:
      dotnet: 7.0
  pre_build:
    commands:
      - dotnet restore CarPoolingWebAPI
  build:
    commands:
      - dotnet publish CarPoolingWebAPI/CarPoolingWebAPI.sln -c Release -o ./output
artifacts:
  files:
    - output/**/*
    
