version: 0.2
phases:
  install:
    runtime-versions:
      dotnet: 6.0
  pre_build:
    commands:
      - dotnet restore CarPoolingWebAPI/carPoolingWebAPI.sln
  build:
    commands:
      - dotnet publish CarPoolingWebAPI/carPoolingWebAPI.sln -c Release -o ./output
  artifacts:
    files:
      - output/**/*
    
